---
title: ":3"
author: "Kenzie"
date: "2025-07-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Packages

library(stringr)
library(knitr)

```

```{r load_data}

# Load the data
raw_data <- read.csv("Meeting 2 Example Data.csv")   # by default, it assumes it's in the file

# Create a copy of the raw data
data <- raw_data

```


```{r restructure}

### Rename Variables ###

# Brackets only affect the elements in the listed order number

colnames(data)[6:15] <- paste0("tipi",
                                rep(c("Ex", "Ag", "Co", "Ne", "Op"), 2),
                                rep(1:2, each=5))

# label which are reverse coded. paste0 either combines before or after each element in the vector

colnames(data)[c(7, 11, 13, 14, 15)] <- paste0(colnames(data)[c(7, 11, 13, 14, 15)], "r")


### Restructure Variables ###

condition_split <- str_split_fixed(data$condition, "_", 2)  # split into 2 columns by underscore

colnames(condition_split) <- c("shock_cause", "moral")

data <- cbind(data, condition_split) # add the split columns to dataframe, append to end

data <- data[, -4]


### Re-code Variables ###

data$guilt == -99

data$guilt <- ifelse(data$guilt == -99,  NA, data$guilt) # if value assign to NA, else remain unchanged in og form


# Make Character variables numeric codes:

# 0 = women, 1, men
data$gender <- factor(data$gender, labels=c(1, 0)) # factor assigns the string as levels of a variable, quantifies each element alphabetically to our number assignments

# 0 = low, 1 = medium, 2 = high
data$shock <- factor(data$shock, labels=c(2, 0, 1))

# 0 = partner, 1 = self
data$shock_cause <- factor(data$shock_cause, labels=c(0,1))

# 0 = bad, 1 = good
data$moral <- factor(data$moral, labels=c(0, 1))


### Reverse Code Variables

data[, c(6, 10, 12:14)] <- 8-data[, c(6, 10, 12:14)]    # c always makes a vector for index values
```

```{r compute}

# Compute personality variables
data$extra <- rowMeans(data[, c(5, 10)])
data$agree <- rowMeans(data[, c(6, 11)])
data$consc <- rowMeans(data[, c(7, 12)])
data$neuro <- rowMeans(data[, c(8, 13)])
data$open <- rowMeans(data[, c(9, 14)])

```


## Codebook for Example Data

```{r codebook}

# rearrange the columns

data <- data[, c(1:3, 5:14, 20:24, 4, 18:19, 15:17)]

# create a codeback
codebook <- data.frame("variable"=colnames(data))

# briefly describe each variable
codebook$description <- c(
  "Participant ID Number",
  "Gender of Participant (0 = Woman, 1 = Man)",
  "Age of Participant",
  "TIPI Extraversion 1",
  "TIPI Agreeableness 1 (R)",
  "TIPI Conscientiousness 1",
  "TIPI Neuroticism 1",
  "TIPI Openness 1",
  "TIPI Extraversion 2 (R)",
  "TIPI Agreeableness 2", 
  "TIPI Conscientiousness 2 (R)",
  "TIPI Neuroticism 2 (R)",
  "TIPI Openness 2 (R)",
  "Composite Extraversion", 
  "Composite Agreeableness", 
  "Composite Conscientiousness", 
  "Composite Neuroticism", 
  "Composite Openness", 
  "Shock Voltage (0 = low, 1 = medium, 2 = high)",
  "Shock Cause (0 = partner, 1 = self)",
  "Partner Morality (0 = bad, 1 = good)",
  "Pre-Shock Generosity ($ shared)",
  "Post-Shock Generosity ($ shared)",
  "Self-Reported Guilt After Shock"
  )

# save the data type for each variable
codebook$type <- sapply(data, class)

# output the codebook as a table
kable(codebook)

```

```{r save}

# export the processes data file
write.csv(data, "Meeting 2 Processed Data.csv", row.names=F) # looks weird in csv as R has their native row names, not necessary

```

